### ISSUE TITLE
Detect uni/multi chain

### ISSUE THREAD

**Issue by btanner** [abhisheknaik96/differential-value-iteration#15]
I have not brought it in yet, but I wrote some code for garet that checks to see if the generated MDP was unichain or not.

I think it would be smart to make this code easy to use for any MDP, so that we can easily tell if we introduce a bug in a hand-made MDP or garet generates one with unexpected properties.

Comments/ideas welcome.

**Comment by abhisheknaik96** [comment]
I just noticed this issue, apologies. 

What procedure do you have in mind for such a check? For prediction, it might involve inspecting the asymptotic state-to-state transition matrix. For control, it doesn't seem as straightforward because by definition, an MDP is multichain if _any_ single stationary policy yields a Markov chain with two or more non-communicating classes of states.

**Comment by btanner** [comment]
@abhisheknaik96 When I made this post, I didn't realize it was so difficult to check. Closing this issue.
